- README.md
We should also document it in the shell hooks list below.
> Fix do-nothing and document genNixActions.

- README.md
To proofread: I wrote this from memory.
> Document bundles and jobs.

- deps.nix
> deep flattening dependencies

- .github/workflows/nix-action-8.10.yml
- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-master.yml
- .nix/nixpkgs.nix
- action.nix
Testing https://github.com/NixOS/nixpkgs/pull/143793
> The verbose output broke the CI: everything passed

- .github/workflows/nix-action-8.10.yml
- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-master.yml
- action.nix
Uses https://github.com/cachix/install-nix-action/pull/105
> Using a more resilient nix installation

- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-master.yml
- .nix/fallback-config.nix
- .nix/nixpkgs.nix
> Update nixpkgs after Coq 8.15 addition.

- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .nix/nixpkgs.nix
Upstream PR on nixpkgs: https://github.com/NixOS/nixpkgs/pull/157033
> Adapt to Coq 8.15 and MathComp 1.14

- .github/workflows/nix-action-8.10.yml
- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .nix/nixpkgs.nix
To get coq-dev to work in Nix based CIs.
> Update nixpkgs after NixOS/nixpkgs#173112

- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/176696
> Test https://github.com/NixOS/nixpkgs/pull/176696

- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .nix/nixpkgs.nix
> Coq 8.16.0 update.

- .github/workflows/nix-action-8.16.yml
- .nix/nixpkgs.nix
> Nixpkgs update enabling many Coq 8.16 packages.

- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .nix/nixpkgs.nix
In preparation of https://github.com/math-comp/analysis/pull/600
> Test split_mathcomp_analysis

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/193520
> Testing hierarchy-builder 1.4.0

- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/193162
> Test mathcomp-analysis-single

- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/202689
> Testing Coq-HoTT

- .github/workflows/nix-action-8.17.yml
- .nix/fallback-config.nix
- .nix/nixpkgs.nix
Following the merge of https://github.com/NixOS/nixpkgs/pull/209145
This would help testing MathComp for instance
> Update nixpkgs for Coq 8.17+rc1

- .github/workflows/nix-action-8.10.yml
- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/220000
> Test https://github.com/NixOS/nixpkgs/pull/220000

- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
https://github.com/NixOS/nixpkgs/pull/223753
> Adding Apery

- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
EDIT Cyril : testing https://github.com/NixOS/nixpkgs/pull/230891 (for cross-referencing, @proux01 please correct if this is the wrong PR)
> MathComp 1.17.0

- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/237928
> testing nixpkgs PR

- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
@proux01
corresponds to https://github.com/NixOS/nixpkgs/pull/238729
> Test infotheo 0.5.2

- .github/workflows/nix-action-8.10.yml
- .github/workflows/nix-action-8.11.yml
- .github/workflows/nix-action-8.12.yml
- .github/workflows/nix-action-8.13.yml
- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-master.yml
- .nix/nixpkgs.nix
- action.nix
Testing https://github.com/NixOS/nixpkgs/pull/251094
> Test hierarchy-builder 1.5.0

- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/251978
> Test coq elpi 1.18.0

- .github/workflows/nix-action-8.18.yml
- .nix/fallback-config.nix
- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/252727
> Test PR 252727

- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
This test PR https://github.com/NixOS/nixpkgs/pull/255303.
> Test Coq 8.18.0

- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
This tests NixOS/nixpkgs#260683
> Test stdpp 1.9.0 and iris 4.1.0

- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
> Test vcfloat addition.

- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
> Test math-classes & CoRN 8.18.0

- .github/workflows/nix-action-8.17.yml
- .nix/nixpkgs.nix
> Test VST 2.12

- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
> Update interval to 4.9.0; add iris-named-props

- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
See https://github.com/NixOS/nixpkgs/pull/265046
> MathComp 1.17 -> 1.18

- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
And update after NixOS/nixpkgs#267378 (gappalib 1.5.4)
> Test NixOS/nixpkgs#267595

- .github/workflows/nix-action-8.15.yml
- .github/workflows/nix-action-8.16.yml
- .nix/nixpkgs.nix
> Update VST to 2.13

- .nix/nixpkgs.nix
This tests NixOS/nixpkgs#280471
> Test QuickChick 2.0.2

- .nix/nixpkgs.nix
This tests NixOS/nixpkgs#281684
> Test smtcoq fix

- .github/workflows/nix-action-8.14.yml
- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.19-mathcomp2.yml
- .github/workflows/nix-action-8.19.yml
- .nix/nixpkgs.nix
This tests NixOS/nixpkgs#290437
> Update nixpkgs (incl. coq-record-update 0.3.3)

- .nix/nixpkgs.nix
> Update Coq 8.19 to 8.19.1

- .github/workflows/nix-action-8.19-mathcomp2.yml
- .github/workflows/nix-action-8.19.yml
- .nix/nixpkgs.nix
This tests https://github.com/NixOS/nixpkgs/pull/295455
> Updates for Coq 8.19

- .github/workflows/nix-action-8.18-mathcomp2.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19-mathcomp2.yml
- .github/workflows/nix-action-8.19.yml
- .nix/nixpkgs.nix
> Enable CompCert for Coq 8.18 & Coq 8.19

- .nix/nixpkgs.nix
Tests: https://github.com/NixOS/nixpkgs/pull/316164
> mathcomp-word: 3.1 → 3.2

- .nix/nixpkgs.nix
This tests https://github.com/NixOS/nixpkgs/pull/322325
> Fix installPhase when using dune

- .nix/nixpkgs.nix
> enable dev overrides

- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17-mathcomp2.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18-mathcomp2.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19-mathcomp2.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20-mathcomp2.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-master.yml
- action.nix
In order to fix a warning in Github interface
> Bump checkout github action version (@v3 -> @v4)

- .github/workflows/nix-action-8.20-mathcomp2.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
https://github.com/coq-community/coq-nix-toolbox/pull/245
> Test stalmarck

- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
> ElmExtraction

- .github/workflows/nix-action-8.19.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/341597
> coqPackages.mtac2: init at 1.4-coq8.19

- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/348516
> coqPackages.json: 0.1.3 -> 0.2.0

- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
This tests NixOS/nixpkgs#349174
> coqutil 0.0.5/0.0.6

- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Following the merge of https://github.com/math-comp/analysis/pull/1349
Testing https://github.com/NixOS/nixpkgs/pull/351897
> coqPackages.mathcomp-reals: init at 1.7

- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/352090
master successfully tested on https://github.com/math-comp/analysis/pull/1373
> Forgotten dependency for mathcomp-altreals

- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/353818
Following https://github.com/math-comp/analysis/pull/1378
> Test renaming of mathcomp-altreals to mathcomp-experimental-reals

- .nix/nixpkgs.nix
Update after NixOS/nixpkgs#359654
> OCaml 5.2.1

- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/364617
> coqPackages.stdlib: init at master (future 9.0)

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/364946
> ocamlPackages.elpi: 2.0.5 -> 2.0.6

- .nix/nixpkgs.nix
Following the merge of https://github.com/coq/coq/pull/19927
Testing https://github.com/NixOS/nixpkgs/pull/367074
> Test coq: keep compiling master

- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/369217
> coqPackages.smtcoq: fix

- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
~https://github.com/NixOS/nixpkgs/pull/359881~
https://github.com/NixOS/nixpkgs/pull/371472
> mathcomp 2.3.0

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/374488
> coq: 8.20.0 -> 8.20.1

- .github/workflows/nix-action-8.16-mathcomp2.yml
- .github/workflows/nix-action-8.16.yml
- .github/workflows/nix-action-8.17.yml
- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/374801
> coqPackages.stdlib: compile some reverse dependencies with Coq master

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/376071
Adapting to https://github.com/math-comp/math-comp/pull/1329
> Test https://github.com/NixOS/nixpkgs/pull/376071

- .github/workflows/nix-action-master.yml
- .nix/nixpkgs.nix
> Test NixOS/nixpkgs#377732

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/379070
> Test coqPackages.coqeal: no longer depends on paramcoq

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/381221
> Test various backports from opam

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/382037
Adapting to https://github.com/math-comp/math-comp/pull/1343
> coqPackages.mathcomp: remove Stdlib dependency

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/382064
> coqPackages.jasmin: init at 2024.07.2

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .github/workflows/nix-action-rocq-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/383074
> Test rocqPackages.rocq-elpi: init at 2.5.0

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/383144
> Test coqPackages.coqeal: 2.0.3 -> 2.1.0

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/384697
> testing mathcomp analysis 1.9.0

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/384770
> Test coqPackages.mathcomp*: update stdlib dependencies

- .github/workflows/nix-action-8.18.yml
- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/373307
> CoqMatrix 1.0.6

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/389454
> rocq-core: 9.0+rc1 -> 9.0.0

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/393385
> Test overrideRocqDerivation

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/403709
Adapt to https://github.com/math-comp/math-comp/pull/1415
> Adapt to https://github.com/math-comp/math-comp/pull/1415

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
> coqPackages.vscoq-language-server: 2.2.1 -> 2.2.5

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing: https://github.com/NixOS/nixpkgs/pull/398851
Cc @hoheinzollern @CohenCyril let's see what happens
> Test coqPackages.mathcomp: 2.3.0 -> 2.4.0

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/405977
> coqPackages.metacoq 1.4

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Nixpkgs PR : https://github.com/NixOS/nixpkgs/pull/406451
> Test coq-elpi Nixpkgs update

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/418179
> coqPackages.*: fix formating

- config-parser-1.0.0/default.nix
Simple change for debugging; you can access jobs by
```
$ nix repl
> :l .
> passthru.setup.instances.<instance>.jobs
```
> Expose jobs on instances

- .github/workflows/nix-action-9.0.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/421022 (I screwed it up)
Testing https://github.com/NixOS/nixpkgs/pull/421216
> coqPackages.*: better formatting fix

- .github/workflows/nix-action-9.0.yml
- .github/workflows/nix-action-rocq-9.0.yml
- .nix/nixpkgs.nix
https://github.com/NixOS/nixpkgs/pull/420742
> rocqPackages.parseque: release version 0.3.0 

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/422128
> coqPackages.VST: adapt to master

- .github/workflows/nix-action-9.1.yml
- .github/workflows/nix-action-rocq-9.1.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/423459
> coqPackages.*: 9.0 -> 9.1

- .github/workflows/nix-action-9.1.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/423752
> coqPackages.*: more 9.0 -> 9.1

- .github/workflows/nix-action-8.18.yml
- .github/workflows/nix-action-8.19.yml
- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .github/workflows/nix-action-9.1.yml
- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/425023
> coqPackages.*: fix Rocq shims for overrides

- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.1.yml
- .nix/nixpkgs.nix
https://github.com/NixOS/nixpkgs/pull/429920
> coqPackages.wasmcert init at 2.1.0

- .nix/nixpkgs.nix
https://github.com/NixOS/nixpkgs/pull/437061
> Test wasmcert release 2.2.0

- .nix/nixpkgs.nix
This tests https://github.com/NixOS/nixpkgs/pull/441484
> Menhir 20250903

- .nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/443157
> Rocq: 9.1+rc1 -> 9.1.0

- .github/workflows/nix-action-8.20.yml
- .github/workflows/nix-action-9.0.yml
- .github/workflows/nix-action-9.1.yml
- .nix/nixpkgs.nix
Tests https://github.com/NixOS/nixpkgs/pull/443549
> Jasmin 2025.06.1

- .github/workflows/nix-action-9.1.yml
- .github/workflows/nix-action-rocq-9.1.yml
- .nix/nixpkgs.nix
Tests https://github.com/NixOS/nixpkgs/pull/445484
> coq-lsp 0.2.4

- .nix/nixpkgs.nix
Test https://github.com/NixOS/nixpkgs/pull/447163
> compcert: enable for Coq 9.0.1

- .github/workflows/nix-action-9.0.yml
- .github/workflows/nix-action-9.1.yml
- .nix/nixpkgs.nix
This tests nixos/nixpkgs#449500
> coqutil 0.0.7
