default.nix
@CohenCyril This is what we did together yesterday. For the record, `nix-shell --argstr job iris` did eventually terminate successfully (opened a shell). However, when trying to build iris, I got:
```
*** Warning: in file tests/string_ident.v, library stdpp.base is required and has not been found in the loadpath!
*** Warning: in file tests/heapprop.v, library stdpp.gmap is required and has not been found in the loadpath!
*** Warning: in file tests/telescopes.v, library stdpp.coPset is required and has not been found in the loadpath!
*** Warning: in file tests/telescopes.v, library stdpp.namespaces is required and has not been found in the loadpath!
COQC iris/prelude/options.v
COQC iris/prelude/prelude.v
File "./iris/prelude/prelude.v", line 2, characters 26-33:
Error: Cannot find a …
```
=> Support the job argument with nix-shell and the _all bundle.

.nix/fallback-config.nix
Related to your answer in #39, I've noticed a possible simplification of the bundle configuration, by relying on the value of `attribute` (which can be set separately from `shell-attribute`). I've verified that `genNixActions` generates the same workflows as before.
=> Simplify bundle config by fixing the value of `attribute`.

.github/workflows/nix-action-master.yml, .github/workflows/nix-action-v8.14.yml, .nix/fallback-config.nix, .nix/nixpkgs.nix
I am facing a new issue: `coqPackages.<package>.job = false` seems like a no-op. I can't get rid of the `coq-shell`, `heq` and `mathcomp-bigenough` reverse dependencies of Coq in the generated workflow.
=> Test development branches of Coq.

template-config.nix
This fixes part of #39 (at least until we clarify if `shell-attribute` should also be a `main-job` and why it isn't in our case.
=> Improve config doc.

.github/workflows/nix-action-8.10.yml, .github/workflows/nix-action-8.11.yml, .github/workflows/nix-action-8.12.yml, .github/workflows/nix-action-8.13.yml, .github/workflows/nix-action-master.yml, .github/workflows/nix-action-v8.14.yml, .nix/shellHook.sh, action.nix, config-parser-1.0.0/default.nix, default.nix
Use `pull_request_target` event instead of `pull_request` to do that. This means that the workflow definition from the base branch will be used instead of the one from the pull request head, and secret variables will be available.
Since `nix-build` runs in an isolated environment, there is no risk of leaking a secret variable.
This is related to https://github.com/coq-community/templates/pull/100 which does the same for the lightweight Nix CI templates.
The `stepCommitToTest` is unused currently and could serve to skip the `actions/checkout@v2` step entirely (in favor of pinning the commit to use with an `--arg override` in all the calls to `nix-build`). I'm leaving it here for now, but we should probably remove it before merging.
I don't know if it would be possible to factorize the …
=> Deploy to Cachix even for PR from forks.

.github/workflows/nix-action-8.10.yml, .github/workflows/nix-action-8.11.yml, .github/workflows/nix-action-8.12.yml, .github/workflows/nix-action-8.13.yml, .github/workflows/nix-action-8.14.yml, .github/workflows/nix-action-8.15.yml, .github/workflows/nix-action-8.16.yml, .github/workflows/nix-action-8.17.yml, .github/workflows/nix-action-master.yml, action.nix, config-parser-1.0.0/default.nix, template-config.nix
This offers a few changes to parameterize which events trigger CI runs:
* ~`pull_request` is run even when action scripts are unchanged (this behavior might have been convenient here but recently proved really confusing in MathComp's CI with CI simply not running on many PRs (maybe due to a change of semantics on github's side, I don't know))~
* ~add an option to not run `pull_request_target`: in MathComp's CI, I found those jobs mostly useless and just cluttering the CI (they can even make it unclear that CI did not run on branches that need a rebase)~ (that was a bad idea, see discussion below)
* add an option to run on `push` on other branches than `master`: this is becoming useful in MathComp with the current situation with two actively developed branches (namely `master` and …
=> Parameterize triggering events

.github/workflows/nix-action-8.10.yml, .github/workflows/nix-action-8.11.yml, .github/workflows/nix-action-8.12.yml, .github/workflows/nix-action-8.13.yml, .github/workflows/nix-action-8.14.yml, .github/workflows/nix-action-8.15.yml, .github/workflows/nix-action-8.16.yml, .github/workflows/nix-action-8.17.yml, .github/workflows/nix-action-8.18.yml, .github/workflows/nix-action-master.yml, action.nix
See commit c4730837f50ae2e1fffed71fe4910a87dbc0a490
It seems we've had the coq nix toolbox silently building nothing maybe during the last three weeks (only realized that when encountering failures on Docker CI in mathcomp whereas Nix CI was all green).
Cc @Zimmi48 @CohenCyril @vbgl
=> Fix assignment after removal of ::set-output

default.nix
Inspired by #163, but doesn't need to wait for a corresponding nixpkgs PR.
=> Add coq-lsp server in nix-shell when available.

.github/workflows/nix-action-8.10.yml, .github/workflows/nix-action-8.11.yml, .github/workflows/nix-action-8.12.yml, .github/workflows/nix-action-8.13.yml, .github/workflows/nix-action-8.14.yml, .github/workflows/nix-action-8.15.yml, .github/workflows/nix-action-8.16.yml, .github/workflows/nix-action-8.17.yml, .github/workflows/nix-action-8.18.yml, .github/workflows/nix-action-master.yml, action.nix
This is an attempt at avoiding duplication of workflows when they are modified (only one of the `pull_request` and `pull_request_target` events should match and the `pull_request` event should only match when the workflow itself has been updated).
=> Fine tune events triggering workflows to avoid running useless jobs.

.github/workflows/nix-action-8.16-mathcomp2.yml, .github/workflows/nix-action-8.17-mathcomp2.yml, .github/workflows/nix-action-8.18-mathcomp2.yml, .nix/fallback-config.nix, .nix/nixpkgs.nix
As discovered when reviewing the update to deriving, lots of versions in `coqPackages` are currently untested because the default MathComp version is still MathComp 1 everywhere. With the addition of these two new workflows for Coq 8.17 and 8.18, we add these missing tests.
Note that ideally, we should avoid rebuilding packages which are unrelated to the MathComp ecosystem (packages that do not depend on MathComp and are not dependencies of other packages depending on MathComp), but I do not see any way to do this filtering other than manual. I tried the manual approach, but it was extremely tedious, and the filtering should evolve depending on what packages and package versions are available in `coqPackages`, which is not realistic if it is done manually.
=> Add workflows for MathComp 2.

.nix/shellHook.sh
NIX_PATH is no longer set for local Nix installs: https://github.com/NixOS/nixpkgs/issues/149791 which was yielding the following error:
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
=> Make cachedMake work with local Nix install and proxy

README.md
There is currently no mention of the important `updateNixToolBox` command in the README, here is an attempt at introducing this.
=> add item in README.md about updateNixToolBox

.github/workflows/nix-action-8.18-mathcomp2.yml, .github/workflows/nix-action-8.18.yml, .nix/nixpkgs.nix, default.nix
Testing nix PR https://github.com/NixOS/nixpkgs/issues/256515
@Zimmi48 this PR includes an extension of the toolbox to add the vscoq2 language server to any shell.
=> Testing vscoq2

README.md
Hi,
We are relying on the coq-nix-toolbox for a formalization of analysis on top of MathComp.
I do not understand the inner working of the coq-nix-toolbox but I occasionally have
to check the README, and, every time, I have the feeling that the purpose is hard
to grasp by a casual user. I therefore propose to add an executive summary at the top of the
README. It is certainly not accurate but I believe that it could help outisders and
maybe trigger the addition of further explanations about the Nix keywords by people more
knowledgeable than me.
Co-authored-by: @proux01
=> proposal for an executive summary

.nix/nixpkgs.nix, .nix/shellHook.sh
This «feature» is disabled by default when using [lix](https://lix.systems) and a string works the same
=> chore(.nix): Don't use url litteral when fetching nixpkgs

.github/workflows/nix-action-8.16-mathcomp2.yml, .github/workflows/nix-action-8.16.yml, .github/workflows/nix-action-8.17.yml, .github/workflows/nix-action-8.18.yml, .github/workflows/nix-action-8.19.yml, .github/workflows/nix-action-8.20.yml, .github/workflows/nix-action-master.yml, action.nix
Fix https://github.com/coq-community/coq-nix-toolbox/pull/296 that was leading to the CI silently being green without even compiling anything.
Discovered in https://coq.zulipchat.com/#narrow/channel/237656-Coq-devs-.26-plugin-devs/topic/CI.20broken
Fixes: #313
=> Fix https://github.com/coq-community/coq-nix-toolbox/pull/296

.github/workflows/nix-action-rocq-9.0.yml, .github/workflows/nix-action-rocq-master.yml, .nix/fallback-config.nix, .nix/shellHook.sh, README.md, config-parser-1.0.0/default.nix, config-parser-1.0.0/overlays.nix, default.nix, project-default.nix, template-config.nix
`rocqPackages` overrides were accidentally ignored in non pure Rocq bundles (i.e. `isRocq` not true).
Also add `.nix/rocq-overlays` directory handling and `coq-override` argument.
=> Fix rocqPackages overrides

.nix/nixpkgs.nix
Testing https://github.com/NixOS/nixpkgs/pull/385748
An overlay we kept for way too long in mathcomp CI.
=> coqPackages.extructures: fix dependency

.github/workflows/nix-action-8.18.yml, .github/workflows/nix-action-8.19.yml, .github/workflows/nix-action-8.20.yml, .github/workflows/nix-action-9.0.yml, .github/workflows/nix-action-master.yml, .github/workflows/nix-action-rocq-9.0.yml, .github/workflows/nix-action-rocq-master.yml, action.nix
This usually happens when a job B depends from a job A and is triggered immediatly after the end of A. Apparently in this case, the result of A is not yet available in the cache. Let's see if waiting a bit improves things.
=> Add a "sleep 30" when trying to build multiple derivations

config-parser-1.0.0/default.nix, config-parser-1.0.0/normalize.nix, config-parser-1.0.0/overlays.nix, template-config.nix
Add no-rocq-yet flag to avoid creating empty rocq package in that case
=> Keep working for packages not ported in rocqPackages yet
